name = "ReEDS2PRAS"
uuid = "c1db39dc-6a9d-11ed-0c9a-05c3ea2a1475"
authors = ["Luke Lavin <luke.lavin@nrel.gov>", "Surya Chandan Dhulipala <suryachandan.dhulipala@nrel.gov>", "Brandon Norton Benton <brandon.benton@nrel.gov"]
version = "0.3.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PRAS = "05348d26-1c52-11e9-35e3-9d51842d34b9"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
ArgParse = "~1.1"
CSV = "~0.10"
DataFrames = "1"
HDF5 = "~0.16"
InlineStrings = "~1.4"
PRAS = "~0.6"
TimeZones = "~1.9"
julia = "^1.6"
